---
title: "DOSPERT_analysis_gather"
output: html_notebook
---

```{r Load Libraries}
# load libraries and data
library(tidyverse)
dospert_raw <- read_csv('/Users/ssp160230/Box/Aging Well Lab/Measures/DOSPERT30/Test Analysis/data/DOSPERT_data.csv')
```

```{r}
# remove unnecessary column for "complete" form status
dospert_wide <- select(dospert_raw, -dospert_complete)
#separate df by risk type to create RT, RP, and RB columns
dospert_rt_long <- dospert_wide[ , 1:31] %>%
  gather(variables, RT, soc_rt_1:eth_rt_6, factor_key = TRUE)
dospert_rp_long <- dospert_wide[ , 32:61] %>%
  gather(variables, RP, soc_rp_1:eth_rp_6, factor_key = TRUE)
dospert_rb_long <- dospert_wide[ , 62:91] %>%
  gather(variables, RB, soc_rb_1:eth_rb_6, factor_key = TRUE)
#separate variable column into domain, risk type, and question number
dospert_rt_long <- dospert_rt_long %>%
  separate(variables, c('domain', 'risk_type', 'q_number'), '_')
dospert_rt_long <- select(dospert_rt_long, -risk_type) #remove risk type column
#bind risk type dfs together to create one long df for all risk types
dospert_long <- cbind(dospert_rt_long, dospert_rp_long, dospert_rb_long)
dospert_clean <- dospert_long %>% #remove redundant variables columns
  select(-variables)
dospert_clean <- arrange(dospert_clean, record_id, domain) #arrange clean df by record id and domain
```

```{r}
#create dospert_sum df with domain subscores for each record_id
dospert_sum <- aggregate(cbind(RT,RP,RB) ~ record_id + domain, data = dospert_clean, FUN = sum)
#sort data by record_id
dospert_sum <- dospert_sum %>%
  arrange(record_id)
```

